"""initial_multitenant_schema

Revision ID: 332bc705e042
Revises: 
Create Date: 2026-04-22 12:25:08.749847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '332bc705e042'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('clerk_org_id', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerk_org_id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('code_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('extension', sa.String(length=20), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('lines_of_code', sa.Integer(), nullable=False),
    sa.Column('indexed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'file_path', name='uq_code_files_tenant_path')
    )
    op.create_index(op.f('ix_code_files_tenant_id'), 'code_files', ['tenant_id'], unique=False)
    op.create_table('impact_analysis',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('requirement', sa.Text(), nullable=False),
    sa.Column('risk_level', sa.String(length=10), nullable=False),
    sa.Column('files_impacted', sa.Integer(), nullable=False),
    sa.Column('modules_impacted', sa.Integer(), nullable=False),
    sa.Column('analysis_summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_impact_analysis_tenant_id'), 'impact_analysis', ['tenant_id'], unique=False)
    op.create_table('integration_audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('story_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_audit_logs_story_id'), 'integration_audit_logs', ['story_id'], unique=False)
    op.create_index(op.f('ix_integration_audit_logs_tenant_id'), 'integration_audit_logs', ['tenant_id'], unique=False)
    op.create_table('oauth_states',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('state_token', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state_token')
    )
    op.create_index(op.f('ix_oauth_states_tenant_id'), 'oauth_states', ['tenant_id'], unique=False)
    op.create_table('platform_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('client_secret', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'platform', name='uq_platform_configs_tenant_platform')
    )
    op.create_index(op.f('ix_platform_configs_tenant_id'), 'platform_configs', ['tenant_id'], unique=False)
    op.create_table('requirements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('requirement_text', sa.Text(), nullable=False),
    sa.Column('requirement_text_hash', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=255), nullable=False),
    sa.Column('intent', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity', sa.String(length=255), nullable=False),
    sa.Column('feature_type', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('business_domain', sa.String(length=100), nullable=False),
    sa.Column('technical_scope', sa.String(length=50), nullable=False),
    sa.Column('estimated_complexity', sa.String(length=10), nullable=False),
    sa.Column('keywords', sa.Text(), nullable=False),
    sa.Column('processing_time_seconds', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requirements_project_id'), 'requirements', ['project_id'], unique=False)
    op.create_index(op.f('ix_requirements_tenant_id'), 'requirements', ['tenant_id'], unique=False)
    op.create_index('ix_requirements_text_hash_project', 'requirements', ['requirement_text_hash', 'project_id'], unique=False)
    op.create_table('source_connections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('access_token', sa.String(length=1024), nullable=False),
    sa.Column('refresh_token', sa.String(length=1024), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('repo_name', sa.String(length=255), nullable=True),
    sa.Column('repo_full_name', sa.String(length=512), nullable=True),
    sa.Column('default_branch', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('oauth_state', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_connections_tenant_id'), 'source_connections', ['tenant_id'], unique=False)
    op.create_table('ticket_integrations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('story_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('project_key', sa.String(length=100), nullable=False),
    sa.Column('issue_type', sa.String(length=100), nullable=False),
    sa.Column('external_ticket_id', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ticket_integrations_story_provider', 'ticket_integrations', ['story_id', 'provider'], unique=False)
    op.create_index(op.f('ix_ticket_integrations_tenant_id'), 'ticket_integrations', ['tenant_id'], unique=False)
    op.create_table('user_stories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('requirement_id', sa.String(length=36), nullable=False),
    sa.Column('impact_analysis_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=255), nullable=False),
    sa.Column('language', sa.String(length=10), server_default='es', nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('story_description', sa.Text(), nullable=False),
    sa.Column('acceptance_criteria', sa.Text(), nullable=False),
    sa.Column('subtasks', sa.Text(), nullable=True),
    sa.Column('definition_of_done', sa.Text(), nullable=False),
    sa.Column('risk_notes', sa.Text(), nullable=False),
    sa.Column('story_points', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=10), nullable=False),
    sa.Column('generation_time_seconds', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_stories_req_analysis', 'user_stories', ['requirement_id', 'impact_analysis_id'], unique=False)
    op.create_index(op.f('ix_user_stories_tenant_id'), 'user_stories', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=255), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerk_user_id')
    )
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('impacted_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['impact_analysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_impacted_files_analysis_id'), 'impacted_files', ['analysis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_impacted_files_analysis_id'), table_name='impacted_files')
    op.drop_table('impacted_files')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_stories_tenant_id'), table_name='user_stories')
    op.drop_index('ix_user_stories_req_analysis', table_name='user_stories')
    op.drop_table('user_stories')
    op.drop_index(op.f('ix_ticket_integrations_tenant_id'), table_name='ticket_integrations')
    op.drop_index('ix_ticket_integrations_story_provider', table_name='ticket_integrations')
    op.drop_table('ticket_integrations')
    op.drop_index(op.f('ix_source_connections_tenant_id'), table_name='source_connections')
    op.drop_table('source_connections')
    op.drop_index('ix_requirements_text_hash_project', table_name='requirements')
    op.drop_index(op.f('ix_requirements_tenant_id'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_project_id'), table_name='requirements')
    op.drop_table('requirements')
    op.drop_index(op.f('ix_platform_configs_tenant_id'), table_name='platform_configs')
    op.drop_table('platform_configs')
    op.drop_index(op.f('ix_oauth_states_tenant_id'), table_name='oauth_states')
    op.drop_table('oauth_states')
    op.drop_index(op.f('ix_integration_audit_logs_tenant_id'), table_name='integration_audit_logs')
    op.drop_index(op.f('ix_integration_audit_logs_story_id'), table_name='integration_audit_logs')
    op.drop_table('integration_audit_logs')
    op.drop_index(op.f('ix_impact_analysis_tenant_id'), table_name='impact_analysis')
    op.drop_table('impact_analysis')
    op.drop_index(op.f('ix_code_files_tenant_id'), table_name='code_files')
    op.drop_table('code_files')
    op.drop_table('tenants')
    # ### end Alembic commands ###
