"""add_redirect_uri_to_oauth_states

Revision ID: 719f4fee3415
Revises: 332bc705e042
Create Date: 2026-04-22 12:43:20.172129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '719f4fee3415'
down_revision: Union[str, Sequence[str], None] = '332bc705e042'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth_states', sa.Column('redirect_uri', sa.String(length=2048), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oauth_states', 'redirect_uri')
    # ### end Alembic commands ###
