"""add_content_column_to_code_files

Revision ID: 88c94e7fd264
Revises: d8a1c3f5e912
Create Date: 2026-04-23 19:46:11.272760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88c94e7fd264'
down_revision: Union[str, Sequence[str], None] = 'd8a1c3f5e912'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code_files', sa.Column('content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('code_files', 'content')
    # ### end Alembic commands ###
