"""widen_token_columns_to_text

Revision ID: 9e9759024c61
Revises: f3c2a1d4e089
Create Date: 2026-04-24 00:19:00.530796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e9759024c61'
down_revision: Union[str, Sequence[str], None] = 'f3c2a1d4e089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('source_connections', 'access_token',
               existing_type=sa.VARCHAR(length=1024),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('source_connections', 'refresh_token',
               existing_type=sa.VARCHAR(length=1024),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('source_connections', 'refresh_token',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=True)
    op.alter_column('source_connections', 'access_token',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=False)
    # ### end Alembic commands ###
