"""story_feedback_and_quality_score

Revision ID: a03dd37be40a
Revises: b4e7f2a1c398
Create Date: 2026-04-28 21:45:37.183516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a03dd37be40a'
down_revision: Union[str, Sequence[str], None] = 'b4e7f2a1c398'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('story_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('rating', sa.String(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['user_stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'story_id', 'user_id', name='uq_story_feedback_per_user')
    )
    op.create_table('story_quality_score',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('story_id', sa.String(length=36), nullable=False),
    sa.Column('completeness', sa.Float(), nullable=False),
    sa.Column('specificity', sa.Float(), nullable=False),
    sa.Column('feasibility', sa.Float(), nullable=False),
    sa.Column('risk_coverage', sa.Float(), nullable=False),
    sa.Column('language_consistency', sa.Float(), nullable=False),
    sa.Column('overall', sa.Float(), nullable=False),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('judge_model', sa.String(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['user_stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('story_id')
    )
    op.drop_index(op.f('ix_connection_audit_logs_connection_id'), table_name='connection_audit_logs')
    op.drop_index(op.f('ix_connection_audit_logs_tenant_id'), table_name='connection_audit_logs')
    op.drop_index(op.f('ix_connection_audit_logs_timestamp'), table_name='connection_audit_logs')
    op.drop_table('connection_audit_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connection_audit_logs',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('connection_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('platform', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('auth_method', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('event', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('actor', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('detail', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('connection_audit_logs_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('connection_audit_logs_pkey'))
    )
    op.create_index(op.f('ix_connection_audit_logs_timestamp'), 'connection_audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_connection_audit_logs_tenant_id'), 'connection_audit_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_connection_audit_logs_connection_id'), 'connection_audit_logs', ['connection_id'], unique=False)
    op.drop_table('story_quality_score')
    op.drop_table('story_feedback')
    # ### end Alembic commands ###
